### ISSUE TITLE
Refactor ./vendor/bin/luyadev repo/update command

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-env-dev#11]
`./vendor/bin/luyadev repos/update`   or simply `./luyadev repos/update` would be more intuitiv than `repo/update` due the directory and actions is done on `repos/`.

Further, what do you think about a script which runs the git push for each repo?

**Comment by nadar** [comment]
1. I don't think its a big difference, its just for developers they should be able to handle this.
2. Its not just pushing, you have to make a branch, **take a look at the diff**, create a commit, and push. Every developer should understand this workflows by its own. its even described here: https://github.com/luyadev/luya-env-dev#changes-collaboration-and-contribution

**Comment by dev7ch** [comment]
1. It`s not a big difference but a mistake imo
2. Usally the master branch stays untouched, why not pushing it directly ( you see the changes at luyadev repos)

**Comment by nadar** [comment]
1. Once learned, you will remember its repo/update instead of repos/update its also written in the guide.
2. Don't understand what you mean but as i said 
> Its not just pushing, you have to make a branch, take a look at the diff, create a commit, and push. Every developer should understand this workflows by its own. its even described here: https://github.com/luyadev/luya-env-dev#changes-collaboration-and-contribution

**Comment by dev7ch** [comment]
ok, i see improvements are not wanted.

in fact the repos/update process is not handy but i dont have time to looong explanations with zero impact.

**Comment by nadar** [comment]
its not about improvements are not welcome, but its easy to blame without concret inputs. if you like we can do a vote to change from `repo/update` to `repos/update` - but i don't believe it will change something. Personally i choose repo cause its more thought about singleton repository: repo/clone repo/remove its just for one repo.
